project:
  type: website
  output-dir: docs

website:
  title: "Iris Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd



format:
  html:
    link-external-newwindow: true
    theme: minty
    css: styles.css
    toc: true

editor: visual

